spring.application.name=essentia
spring.application.version=v1.0

# Mongo
spring.data.mongodb.host=localhost
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.port=27017
spring.data.mongodb.database=essentia-dev
spring.data.mongodb.username=Root
spring.data.mongodb.password=root


# jwt
app.jwt.secret=a3IR6wurgqL1OTIUH2RuI+zfeNePD34i1xAf+kwaJQU=
app.jwt.expirationMs=3600000
#1 hora de codigo
app.cors.allowed-origins=*
app.jwt.issuer=essentia-api


#docs
scalar.enabled=true
scalar.url=http://localhost:8080/v3/api-docs
scalar.path=/docs
