spring.application.name=essentia
spring.application.version=v1.0

# Mongo
spring.data.mongodb.host=localhost
spring.data.mongodb.uri=mongodb://Root:root@localhost:??????/essentia-dev?authSource=admin
spring.data.mongodb.authentication-database=??????
spring.data.mongodb.port=??????
spring.data.mongodb.database=essentia-dev

# jwt
app.jwt.secret=??????
app.jwt.expirationMs=3600000
#1 hora de codigo
app.cors.allowed-origins=*
app.jwt.issuer=essentia-api


#docs
scalar.enabled=true
scalar.url=http://localhost:8080/v3/api-docs
scalar.path=/docs
